/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectomeia;

import Conexion.BDD;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.Date;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author luise
 */
public class frmCorreos extends javax.swing.JFrame {

    /**
     * Creates new form frmCorreos
     */
    public frmCorreos() {
        initComponents();
        cmbSeleccionarLocal.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtBandejaEntrada = new javax.swing.JTextArea();
        btnActualizarEntrada = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnActualizarSalida = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtBandejaSalida = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        btnEnviarUsuarioLocal = new javax.swing.JButton();
        btnEnviarListaLocal = new javax.swing.JButton();
        cmbSeleccionarLocal = new javax.swing.JComboBox<>();
        lblSeleccionar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMensajeLocal = new javax.swing.JTextArea();
        txtAsuntoLocal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtAdjuntoLocal = new javax.swing.JTextField();
        btnExaminarAdjuntoLocal = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnEnviarLocal = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        cmbGrupo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtAsuntoGrupos = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMensajeGrupos = new javax.swing.JTextArea();
        txtUsuarioGrupos = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnEnviarGrupos = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        txtBandejaEntrada.setEditable(false);
        txtBandejaEntrada.setColumns(20);
        txtBandejaEntrada.setRows(5);
        jScrollPane4.setViewportView(txtBandejaEntrada);

        btnActualizarEntrada.setText("Actualizar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnActualizarEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnActualizarEntrada)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Bandeja de entrada", jPanel1);

        btnActualizarSalida.setText("Actualizar");

        txtBandejaSalida.setEditable(false);
        txtBandejaSalida.setColumns(20);
        txtBandejaSalida.setRows(5);
        jScrollPane5.setViewportView(txtBandejaSalida);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnActualizarSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnActualizarSalida)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );

        jTabbedPane1.addTab("Bandeja de salida", jPanel2);

        btnEnviarUsuarioLocal.setText("Enviar a un usuario");
        btnEnviarUsuarioLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarUsuarioLocalActionPerformed(evt);
            }
        });

        btnEnviarListaLocal.setText("Enviar a una lista");
        btnEnviarListaLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarListaLocalActionPerformed(evt);
            }
        });

        cmbSeleccionarLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSeleccionarLocalActionPerformed(evt);
            }
        });

        lblSeleccionar.setText("Seleccione el usuario");

        txtMensajeLocal.setColumns(20);
        txtMensajeLocal.setRows(5);
        jScrollPane1.setViewportView(txtMensajeLocal);

        jLabel1.setText("Asunto");

        jLabel2.setText("Mensaje");

        txtAdjuntoLocal.setEnabled(false);

        btnExaminarAdjuntoLocal.setText("Examinar");
        btnExaminarAdjuntoLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExaminarAdjuntoLocalActionPerformed(evt);
            }
        });

        jLabel3.setText("Adjuntar archivo");

        btnEnviarLocal.setText("Enviar correo");
        btnEnviarLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarLocalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(txtAsuntoLocal)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtAdjuntoLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExaminarAdjuntoLocal, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnEnviarUsuarioLocal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEnviarListaLocal))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(cmbSeleccionarLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblSeleccionar))
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(btnEnviarLocal))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnviarUsuarioLocal)
                    .addComponent(btnEnviarListaLocal))
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbSeleccionarLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSeleccionar))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAsuntoLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAdjuntoLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExaminarAdjuntoLocal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEnviarLocal)
                .addGap(40, 40, 40))
        );

        jTabbedPane1.addTab("Enviar correo (Local)", jPanel3);

        cmbGrupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13" }));

        jLabel4.setText("Asunto");

        jLabel5.setText("Mensaje");

        txtMensajeGrupos.setColumns(20);
        txtMensajeGrupos.setRows(5);
        jScrollPane2.setViewportView(txtMensajeGrupos);

        jLabel6.setText("Ingrese Nombre de Usuario");

        btnEnviarGrupos.setText("Enviar correo");
        btnEnviarGrupos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarGruposActionPerformed(evt);
            }
        });

        jLabel7.setText("Seleccione el grupo");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(71, 71, 71)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUsuarioGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addComponent(btnEnviarGrupos))
                .addContainerGap(209, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2)
                        .addComponent(txtAsuntoGrupos)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5))
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addContainerGap()))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUsuarioGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 336, Short.MAX_VALUE)
                .addComponent(btnEnviarGrupos)
                .addGap(22, 22, 22))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(128, 128, 128)
                    .addComponent(jLabel4)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(txtAsuntoGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(14, 14, 14)
                    .addComponent(jLabel5)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(72, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Enviar correo (Otros grupos)", jPanel4);

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addComponent(btnRegresar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRegresar)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbSeleccionarLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSeleccionarLocalActionPerformed
        
    }//GEN-LAST:event_cmbSeleccionarLocalActionPerformed

    private void btnEnviarUsuarioLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarUsuarioLocalActionPerformed
        // TODO add your handling code here:
        cmbSeleccionarLocal.removeAllItems();                        
        
        try {
            OperacionesSecuencial.LlenarUsuariosMaestro();
        } catch (IOException ex) {
            Logger.getLogger(frmCorreos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        LinkedList<Usuario> usuarios = OperacionesSecuencial.obtenerUsuarios(2);
        for (int i = 0; i < usuarios.size(); i++) {
            if(usuarios.get(i).getEstatus() != 0){
                cmbSeleccionarLocal.addItem(usuarios.get(i).getUsuario());                
            }            
        }
        
        cmbSeleccionarLocal.setEnabled(true);
    }//GEN-LAST:event_btnEnviarUsuarioLocalActionPerformed

    private void btnEnviarListaLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarListaLocalActionPerformed
        // TODO add your handling code here:
        cmbSeleccionarLocal.removeAllItems();
        
        try {
            SecuencialLista.LlenarListasMaestro();
        } catch (IOException ex) {
            Logger.getLogger(frmCorreos.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        LinkedList<Lista> listas = SecuencialLista.obtenerListas(2);        
        for (int i = 0; i < listas.size(); i++) {
            if(listas.get(i).getUsuario().equals(ProyectoMEIA.usuarioEnUso.getUsuario()) && listas.get(i).getEstatus() != 0){
                cmbSeleccionarLocal.addItem(listas.get(i).getNombreLista());
            }
        }
        
        cmbSeleccionarLocal.setEnabled(true);
    }//GEN-LAST:event_btnEnviarListaLocalActionPerformed

    private void btnExaminarAdjuntoLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExaminarAdjuntoLocalActionPerformed
        // TODO add your handling code here:
        JFileChooser dialogo = new JFileChooser();        
        File ficheroImagen;
        String rutaArchivo;        
        int valor = dialogo.showOpenDialog(this);
        if (valor == JFileChooser.APPROVE_OPTION) {
            ficheroImagen = dialogo.getSelectedFile();
            rutaArchivo = ficheroImagen.getPath();

                
            txtAdjuntoLocal.setText(rutaArchivo);            
        }
    }//GEN-LAST:event_btnExaminarAdjuntoLocalActionPerformed

    private void btnEnviarLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarLocalActionPerformed
        // TODO add your handling code here:
        if(!txtAsuntoLocal.getText().isEmpty() && !txtMensajeLocal.getText().isEmpty() && !cmbSeleccionarLocal.getSelectedItem().toString().isEmpty()){
            Date fecha = new Date();
            
            Correo correo = new Correo(ProyectoMEIA.usuarioEnUso.getUsuario(), cmbSeleccionarLocal.getSelectedItem().toString(), fecha.toGMTString(),
                    txtAsuntoLocal.getText().toString(),txtMensajeLocal.getText().toString(), txtAdjuntoLocal.getText().toString(), 1);
            
            ArchivoArbolBinario.EnviarCorreo(correo);
        }
        else{
            JOptionPane.showMessageDialog(null, "Debe ingresar el asunto, mensaje, y el destinatario");
        }
    }//GEN-LAST:event_btnEnviarLocalActionPerformed

    private void btnEnviarGruposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarGruposActionPerformed
        // TODO add your handling code here:
        if(!txtMensajeGrupos.getText().isEmpty() && !cmbGrupo.getSelectedItem().toString().isEmpty() && !txtAsuntoGrupos.getText().toString().isEmpty()
                && !txtUsuarioGrupos.getText().isEmpty()){
            Date fecha = new Date();
            
            Correo correo = new Correo(ProyectoMEIA.usuarioEnUso.getUsuario(), txtUsuarioGrupos.getText().toString(), fecha.toGMTString(), 
                    txtAsuntoGrupos.getText().toString(), txtMensajeGrupos.getText().toString(), "NULL", 1);
            
            try {
                BDD.getInstancia().conexion();
                BDD.getInstancia().Insert(13, Integer.parseInt(cmbGrupo.getSelectedItem().toString()), ProyectoMEIA.usuarioEnUso.getUsuario(),
                        txtUsuarioGrupos.getText().toString(), txtAsuntoGrupos.getText().toString(), txtMensajeGrupos.getText().toString());                                
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(frmCorreos.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(frmCorreos.class.getName()).log(Level.SEVERE, null, ex);
            }                        
        }
        else{
            JOptionPane.showMessageDialog(null, "Debe ingresar el asunto, mensaje, y el destinatario");
        }
    }//GEN-LAST:event_btnEnviarGruposActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        if(ProyectoMEIA.usuarioEnUso.getRol() == 1){
            OpcionesAdministrador opcionesAdministrador = new OpcionesAdministrador();
            opcionesAdministrador.setVisible(true);
            this.setVisible(false);
        }
        else{
            OpcionesUsuario opcionesUsuario = new OpcionesUsuario();
            opcionesUsuario.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCorreos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCorreos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCorreos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCorreos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCorreos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarEntrada;
    private javax.swing.JButton btnActualizarSalida;
    private javax.swing.JButton btnEnviarGrupos;
    private javax.swing.JButton btnEnviarListaLocal;
    private javax.swing.JButton btnEnviarLocal;
    private javax.swing.JButton btnEnviarUsuarioLocal;
    private javax.swing.JButton btnExaminarAdjuntoLocal;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cmbGrupo;
    private javax.swing.JComboBox<String> cmbSeleccionarLocal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblSeleccionar;
    private javax.swing.JTextField txtAdjuntoLocal;
    private javax.swing.JTextField txtAsuntoGrupos;
    private javax.swing.JTextField txtAsuntoLocal;
    private javax.swing.JTextArea txtBandejaEntrada;
    private javax.swing.JTextArea txtBandejaSalida;
    private javax.swing.JTextArea txtMensajeGrupos;
    private javax.swing.JTextArea txtMensajeLocal;
    private javax.swing.JTextField txtUsuarioGrupos;
    // End of variables declaration//GEN-END:variables
}
