/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectomeia;

import java.io.IOException;
import java.util.Date;
import java.util.LinkedList;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author garya
 */
public class ManejodeListas extends javax.swing.JFrame {

    /**
     * Creates new form ManejodeListas
     */
    public ManejodeListas() throws IOException {
        initComponents();
        if(SecuencialLista.obtenerDescriptorLista(2).getNumRegistros()!=0){
             SecuencialLista.LlenarListasMaestro();
        }
       
        LlenarCombobox();
    
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtDesc = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnIngresar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CBListas = new javax.swing.JComboBox<>();
        txtDescM = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        RDActivado = new javax.swing.JRadioButton();
        RDDesactivado = new javax.swing.JRadioButton();
        btnModificar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        CBUsuarios = new javax.swing.JComboBox<>();
        btnBuscar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        CBListas2 = new javax.swing.JComboBox<>();
        btnEliminar = new javax.swing.JButton();
        CBUsuario2 = new javax.swing.JComboBox<>();
        btnSalir = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jLabel3.setText("Nueva Lista");

        jLabel5.setText("Nombre");

        jLabel6.setText("Descripcion");

        btnIngresar.setText("Aceptar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(btnIngresar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(btnIngresar)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ingresar Lista", jPanel1);

        jLabel1.setText("Modificar");

        jLabel2.setText("Nombre");

        jLabel4.setText("Descripcion");

        RDActivado.setText("Activado");
        RDActivado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RDActivadoActionPerformed(evt);
            }
        });

        RDDesactivado.setText("Desactivado");
        RDDesactivado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RDDesactivadoActionPerformed(evt);
            }
        });

        btnModificar.setText("Aceptar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        jLabel8.setText("Usuario");

        btnBuscar.setText("Aceptar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(104, 104, 104))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CBListas, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CBUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(btnBuscar))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDescM, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(RDActivado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RDDesactivado))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(btnModificar)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CBListas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CBUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(btnBuscar)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RDActivado)
                    .addComponent(RDDesactivado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnModificar)
                .addGap(22, 22, 22))
        );

        jTabbedPane1.addTab("Modificar Lista", jPanel2);

        jLabel7.setText("Eliminar");

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jLabel7))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(btnEliminar))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CBUsuario2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CBListas2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CBListas2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(CBUsuario2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEliminar)
                .addContainerGap(124, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Eliminar Lista", jPanel3);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(btnSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:
        Date fechaActual = new Date();
        if(VerificarCampos()){
            Lista nuevaLista=new Lista(txtNombre.getText(),ProyectoMEIA.usuarioEnUso.getUsuario(),txtDesc.getText(),0,fechaActual.toString(),1);
            if(SecuencialLista.obtenerDescriptorLista(2).getNumRegistros()< SecuencialLista.obtenerDescriptorLista(2).getMaxReorganizacion()){
                if(!VerificarLlaves(nuevaLista)){
                    String textoAnterior="";
                    boolean PrimerIngreso=false;
                    if(SecuencialLista.obtenerDescriptorLista(2).numRegistros!=0){
                        textoAnterior=Lector.Obtener("C:/MEIA/bitacora_lista.txt");
                        PrimerIngreso=true;
                    }
                     Escritor.Escribir("C:/MEIA/bitacora_lista.txt", textoAnterior+nuevaLista.toString());  
                       DescriptorLista des = SecuencialLista.obtenerDescriptorLista(2);
                            
                            des.setNumRegistros(des.getNumRegistros()+1);
                            des.setRegistrosActivos(des.getRegistrosActivos()+1);                            
                            des.setUsuarioModificacion(nuevaLista.getUsuario());
                            des.setFechaModificacion(fechaActual.toString());
                            if(PrimerIngreso==true){
                                des.setFechaCreacion(fechaActual.toString());
                                des.setUsuarioCreacion(ProyectoMEIA.usuarioEnUso.getUsuario()); 
                            }
                            SecuencialLista.rellenarDescriptorLista(des, 2);
                            JOptionPane.showMessageDialog(null,"Lista ingresada");
                            txtDesc.setText("");
                            txtNombre.setText("");
                            LlenarCombobox();
                }
                else{
                    JOptionPane.showMessageDialog(null,"Lista ya Existente");
                    txtNombre.setText("");
                }
            }
            else{
                try {
                    SecuencialLista.LlenarListasMaestro();
                    if(!VerificarLlaves(nuevaLista)){
                    String textoAnterior="";
                    if(SecuencialLista.obtenerDescriptorLista(2).numRegistros!=0){
                        textoAnterior=Lector.Obtener("C:/MEIA/bitacora_lista.txt");
                    }
                     Escritor.Escribir("C:/MEIA/bitacora_lista.txt", textoAnterior+nuevaLista.toString());  
                       DescriptorLista des = SecuencialLista.obtenerDescriptorLista(2);
                            
                            des.setNumRegistros(des.getNumRegistros()+1);
                            des.setRegistrosActivos(des.getRegistrosActivos()+1);                            
                            des.setUsuarioModificacion(nuevaLista.getUsuario());
                            des.setFechaModificacion(fechaActual.toString());

                        
                            SecuencialLista.rellenarDescriptorLista(des, 2);
                            JOptionPane.showMessageDialog(null,"Lista ingresada");
                            txtDesc.setText("");
                            txtNombre.setText("");
                            LlenarCombobox();
                }
                else{
                    JOptionPane.showMessageDialog(null,"Lista ya Existente");
                    txtNombre.setText("");
                }
                } catch (IOException ex) {
                    Logger.getLogger(ManejodeListas.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                
            }
        }
        else{
            JOptionPane.showMessageDialog(null,"Los campos deben estar lleno");
        }
    }//GEN-LAST:event_btnIngresarActionPerformed
    public void LlenarCombobox(){
        CBListas.removeAllItems();
        CBListas2.removeAllItems();
        CBUsuarios.removeAllItems();
        CBUsuario2.removeAllItems();
        if(SecuencialLista.obtenerDescriptorLista(1).getNumRegistros()!=0){
            SecuencialLista.obtenerListas(2).forEach((list) -> {CBListas.addItem(list.getNombreLista());CBListas2.addItem(list.getNombreLista());});
         }
        if(SecuencialLista.obtenerDescriptorLista(2).getNumRegistros()!=0){
             SecuencialLista.obtenerListas(1).forEach((list) -> {CBListas.addItem(list.getNombreLista());CBListas2.addItem(list.getNombreLista());});
        }
       if(OperacionesSecuencial.obtenerDescriptorUsuario(1).getNumRegistros()!=0){
            OperacionesSecuencial.obtenerUsuarios(2).stream().map((user) -> {CBUsuarios.addItem(user.getUsuario());return user;}).forEachOrdered((user) -> {CBUsuario2.addItem(user.getUsuario());});
        }
       if(OperacionesSecuencial.obtenerDescriptorUsuario(2).getNumRegistros()!=0){
            OperacionesSecuencial.obtenerUsuarios(1).stream().map((user) -> {CBUsuarios.addItem(user.getUsuario());return user;}).forEachOrdered((user) -> {CBUsuario2.addItem(user.getUsuario());});
        }
    }
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
            Lista listaEncontrada=EncontrarLista(CBListas.getSelectedItem().toString(),CBUsuarios.getSelectedItem().toString());
            if(listaEncontrada!=null){
                txtDescM.setText(listaEncontrada.getDescripcion());
                if(listaEncontrada.getEstatus()==0){
                    RDDesactivado.setSelected(true);
                     RDActivado.setSelected(false);
                }
                else if(listaEncontrada.getEstatus()==1){
                     RDDesactivado.setSelected(false);
                     RDActivado.setSelected(true);
                }
                
            }
            else{
                JOptionPane.showMessageDialog(null,"Lista no encontrada");
            }
        } catch (IOException ex) {
            Logger.getLogger(ManejodeListas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        boolean estadoAntes=false,estadoDespues=false;
        LinkedList<Lista> lista=SecuencialLista.obtenerListas(2);
        if(VerificarCamposModificacion()){
            for (int i = 0; i < lista.size(); i++) {
                if(lista.get(i).getNombreLista().equals(CBListas.getSelectedItem())&&lista.get(i).getUsuario().equals(CBUsuarios.getSelectedItem())){
                    lista.get(i).setDescripcion(txtDescM.getText());
                    if(lista.get(i).getEstatus()==1){
                         estadoAntes=true;
                    }
                    else if(lista.get(i).getEstatus()==0){
                         estadoAntes=false;
                    }
                   
                    if(RDActivado.isSelected()==true){
                        lista.get(i).setEstatus(1);
                        estadoDespues=true;
                    }
                    else if(RDDesactivado.isSelected()==true){
                        lista.get(i).setEstatus(0);
                         estadoDespues=false;
                    }
                }
            }
         SecuencialLista.rellenarListasMaestro(lista);
        DescriptorLista listado= SecuencialLista.obtenerDescriptorLista(1);
        Date fecha=new Date();
        listado.setFechaModificacion(fecha.toString());
        listado.setUsuarioModificacion(ProyectoMEIA.usuarioEnUso.getUsuario());
        if(estadoAntes==true&&estadoDespues==false){
            listado.setRegistrosActivos(listado.getRegistrosActivos()-1);
            listado.setRegistrosInactivos(listado.getRegistrosInactivos()+1);
        }
        else if(estadoAntes==false&&estadoDespues==true){
            listado.setRegistrosActivos(listado.getRegistrosActivos()+1);
            listado.setRegistrosInactivos(listado.getRegistrosInactivos()-1);          
        }
                  
        

        SecuencialLista.rellenarDescriptorLista(listado, 1);
        JOptionPane.showMessageDialog(null, "Lista Modificada");
        txtDescM.setText("");
        RDActivado.setSelected(false);
        RDDesactivado.setSelected(false);
        }
        else{
            JOptionPane.showMessageDialog(null,"Los campos deben estar llenos");
        }
      
       
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        try {
            // TODO add your handling code here:
           SecuencialLista.LlenarListasMaestro();
           boolean listaEncontrada=false;
             LinkedList<Lista> lista=SecuencialLista.obtenerListas(2);
             for (int i = 0; i < SecuencialLista.obtenerListas(2).size(); i++) {
                 if(lista.get(i).getNombreLista().equals(CBListas2.getSelectedItem().toString())&& lista.get(i).getUsuario().equals(CBUsuario2.getSelectedItem().toString())){
                     lista.get(i).setEstatus(0);
                     listaEncontrada=true;
                 }
            }
             SecuencialLista.rellenarListasMaestro(lista);
            DescriptorLista desc=SecuencialLista.obtenerDescriptorLista(1);
            desc.setRegistrosActivos(desc.getRegistrosActivos()-1);
            desc.setRegistrosInactivos(desc.getRegistrosActivos()+1);
            SecuencialLista.rellenarDescriptorLista(desc, 1);
            if(listaEncontrada==true){
               JOptionPane.showMessageDialog(null,"Lista Eliminada");  
               LlenarCombobox();
            }
            else{
                JOptionPane.showMessageDialog(null,"Lista no encontrada"); 
            }
           
        } catch (IOException ex) {
            Logger.getLogger(ManejodeListas.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void RDActivadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RDActivadoActionPerformed
        // TODO add your handling code here:
        RDDesactivado.setSelected(false);
    }//GEN-LAST:event_RDActivadoActionPerformed

    private void RDDesactivadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RDDesactivadoActionPerformed
        // TODO add your handling code here:
         RDActivado.setSelected(false);
    }//GEN-LAST:event_RDDesactivadoActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
          OpcionesAdministrador registro = new OpcionesAdministrador();
                        registro.setVisible(true);
                        this.setVisible(false);
    }//GEN-LAST:event_btnSalirActionPerformed
    public boolean VerificarCamposModificacion(){
        if(txtDescM.getText().equals("")){
            return false;
        }
        else if(RDActivado.isSelected()==false && RDDesactivado.isSelected()==false){
            return false;
        }
        else{
            return true;
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManejodeListas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManejodeListas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManejodeListas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManejodeListas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ManejodeListas().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(ManejodeListas.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    public boolean VerificarCampos(){
        if(txtNombre.getText().isEmpty())
            return false;
        return !txtDesc.getText().isEmpty();
    }
    public boolean VerificarLlaves(Lista list){
       boolean Encontrado=false;
       if(SecuencialLista.obtenerDescriptorLista(2).getNumRegistros()!=0){
         for(Lista elemento:SecuencialLista.obtenerListas(1)){
           if(elemento.getNombreLista().equals(list.getNombreLista()) && elemento.getUsuario().equals(list.getUsuario())){
               Encontrado = true;
           }
          }  
       }
       if(SecuencialLista.obtenerDescriptorLista(1).getNumRegistros()!=0){
         for(Lista elemento:SecuencialLista.obtenerListas(2)){
           if(elemento.getNombreLista().equals(list.getNombreLista()) && elemento.getUsuario().equals(list.getUsuario())){
               Encontrado = true;
           }
         }         
       }
       return Encontrado;
    }
    public Lista EncontrarLista(String nombre,String usuario) throws IOException{
        Lista ListaEncontrada=null;
              SecuencialLista.LlenarListasMaestro();        
        for(Lista list:SecuencialLista.obtenerListas(2)){
            if(list.getNombreLista().equals(nombre)&&list.getUsuario().equals(usuario)){
                ListaEncontrada=list;
            }
        }
        return ListaEncontrada;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBListas;
    private javax.swing.JComboBox<String> CBListas2;
    private javax.swing.JComboBox<String> CBUsuario2;
    private javax.swing.JComboBox<String> CBUsuarios;
    private javax.swing.JRadioButton RDActivado;
    private javax.swing.JRadioButton RDDesactivado;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField txtDesc;
    private javax.swing.JTextField txtDescM;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
